improve ec2 scripts a little bit

diff --git a/extras/ec2/bin/launch-katta-master b/extras/ec2/bin/launch-katta-master
--- a/extras/ec2/bin/launch-katta-master
+++ b/extras/ec2/bin/launch-katta-master
@@ -67,6 +67,10 @@ fi
 
 # Finding Katta image
 AMI_IMAGE=`ec2-describe-images -a | grep $S3_BUCKET | grep $KATTA_VERSION | grep $ARCH | grep available | awk '{print $2}'`
+if [ -z "$AMI_IMAGE" ]; then
+	echo "could not find a ami with S3_BUCKET=${S3_BUCKET}, KATTA_VERSION=${KATTA_VERSION}, ARCH=${ARCH}"
+	exit 1
+fi
 
 # Start a master
 echo "Starting master with AMI $AMI_IMAGE"
@@ -77,13 +81,13 @@ while true; do
   # get private dns
   MASTER_HOST=`ec2-describe-instances $INSTANCE | grep running | awk '{print $5}'`
   if [ ! -z $MASTER_HOST ]; then
-    echo "Started as $MASTER_HOST"
     break;
   fi
   sleep 1
 done
 
 MASTER_EC2_HOST=`ec2-describe-instances $INSTANCE | grep INSTANCE | grep running | grep $MASTER_HOST | awk '{print $4}'`
+echo "Started as $MASTER_HOST / $MASTER_EC2_HOST"
 echo $MASTER_HOST > $MASTER_PRIVATE_IP_PATH
 echo $MASTER_EC2_HOST > $MASTER_IP_PATH
 MASTER_EC2_ZONE=`ec2-describe-instances $INSTANCE | grep INSTANCE | grep running | grep $MASTER_HOST | awk '{print $11}'`
